"""Fidelity test: the Python cross-reactivity port must match the frontend.

`cross_reactivity_fixtures.json` is generated by running the ACTUAL frontend
`crossReactivity.ts` functions (via `node --experimental-strip-types`) over a set
of representative inputs. These tests assert the Python port reproduces that
output byte-for-byte, so the server derivation can't silently drift from the
curated source the app has always used.

Regenerate the fixtures (only when the map/logic intentionally changes):
  node --experimental-strip-types <script importing crossReactivity.ts> \
    emitting {prioritized:[{confirmed,reaction,out}], suspect:[{name,reaction,out}]}
"""
import json
from pathlib import Path

from app.services.allergy.cross_reactivity import (
    CROSS_REACTIVITY_MAP,
    get_suspected_ingredients_prioritized,
    is_cross_reactive_suspect,
)

_FIXTURES = json.loads(
    (Path(__file__).parent / "cross_reactivity_fixtures.json").read_text(encoding="utf-8")
)


def test_map_loaded():
    # extracted from the frontend: 59 allergens / 277 edges
    assert len(CROSS_REACTIVITY_MAP) == 59
    assert sum(len(v) for v in CROSS_REACTIVITY_MAP.values()) == 277


def test_prioritized_matches_frontend_reference():
    for case in _FIXTURES["prioritized"]:
        got = get_suspected_ingredients_prioritized(case["confirmed"], case["reaction"])
        assert got == case["out"], f"mismatch for confirmed={case['confirmed']} reaction={case['reaction']}"


def test_is_suspect_matches_frontend_reference():
    for case in _FIXTURES["suspect"]:
        got = is_cross_reactive_suspect(case["name"], case["reaction"])
        assert got == case["out"], f"mismatch for {case['name']} / {case['reaction']}"


# ── report integration (Phase 4) ─────────────────────────────────────────────

from datetime import date, datetime, timezone
from types import SimpleNamespace

from app.services.allergy.report import build_report, generate_pdf


def _confirmed(name):
    return SimpleNamespace(ingredient=SimpleNamespace(name=name), confirmed_date=date(2025, 1, 1), note=None)


def test_report_includes_cross_reactive_suspects():
    baby = SimpleNamespace(name="테스트아기", birth_date=date(2025, 1, 1))
    now = datetime(2026, 1, 1, tzinfo=timezone.utc)
    report = build_report(baby, [], [_confirmed("우유")], now, now)
    names = {s.suspected_name for s in report.suspected_cross_reactive}
    assert names, "우유 확진 → 교차반응 의심 재료가 있어야 함"
    assert "우유" not in names  # 자기 자신은 제외
    assert all(s.source_allergen == "우유" for s in report.suspected_cross_reactive)


def test_report_no_suspects_when_no_allergens():
    baby = SimpleNamespace(name="테스트아기", birth_date=date(2025, 1, 1))
    now = datetime(2026, 1, 1, tzinfo=timezone.utc)
    report = build_report(baby, [], [], now, now)
    assert report.suspected_cross_reactive == []


def test_report_pdf_renders_with_suspects():
    # the new template section must render without a Jinja/weasyprint error
    baby = SimpleNamespace(name="테스트아기", birth_date=date(2025, 1, 1))
    now = datetime(2026, 1, 1, tzinfo=timezone.utc)
    report = build_report(baby, [], [_confirmed("우유")], now, now)
    pdf = generate_pdf(report)
    assert pdf[:4] == b"%PDF" and len(pdf) > 1000
